name: MATLAB Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up virtual display
        run: |
            sudo apt-get install -y xvfb
            Xvfb :99 -screen 0 1920x1080x24 -dpi 96 -noreset
            echo "DISPLAY=:99" >> $GITHUB_ENV
      
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
      
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd); main