name: MATLAB Test
on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath(pwd); main